### PR TITLE
Add a simple benchmark

### PR DESCRIPTION
**Pull request by rbasso**
To make the project's structure complete, I added a example benchmark.

To run the benchmark, just type:

```
stack bench
```

Or, *if you are using Stack with **Nix***:

```
stack bench --no-nix-pure
```

To create a [beautiful HTML output](http://www.serpentine.com/criterion/fibber.html), type:

```
stack bench --benchmark-arguments='--output=benchmark.html'
```

Or, *if you are using Stack with **Nix***:
```
stack bench --no-nix-pure --benchmark-arguments='--output=benchmark.html'
```

### CODE REVIEW

**Comment by yugawara** [comment]
[yasu@nixos:~/disclaimer]$ stack bench --benchmark-arguments='--output=benchmark.html'
disclaimer-0.1.0.0: benchmarks
Running 1 benchmarks...
Benchmark bench: RUNNING...
benchmarking rectArea/unit square
time                 8.809 ns   (8.807 ns .. 8.811 ns)
bench: <stdout>: commitBuffer: invalid argument (invalid character)
                     1.000 RBenchmark bench: ERROR

--  While building package disclaimer-0.1.0.0 using:
      /home/yasu/.stack/setup-exe-cache/x86_64-linux-nix/Cabal-simple_mPHDZzAJ_1.24.2.0_ghc-8.0.2 --builddir=.stack-work/dist/x86_64-linux-nix/Cabal-1.24.2.0 bench bench --benchmark-options=--output=benchmark.html
    Process exited with code: ExitFailure 1

[yasu@nixos:~/disclaimer]$ stack bench --benchmark-arguments='--output=/tmp/benchmark.html'
disclaimer-0.1.0.0: benchmarks
Running 1 benchmarks...
Benchmark bench: RUNNING...
benchmarking rectArea/unit square
time                 8.804 ns   (8.802 ns .. 8.805 ns)
bench: <stdout>: commitBuffer: invalid argument (invalid character)
                     1.000 RBenchmark bench: ERROR

--  While building package disclaimer-0.1.0.0 using:
      /home/yasu/.stack/setup-exe-cache/x86_64-linux-nix/Cabal-simple_mPHDZzAJ_1.24.2.0_ghc-8.0.2 --builddir=.stack-work/dist/x86_64-linux-nix/Cabal-1.24.2.0 bench bench --benchmark-options=--output=/tmp/benchmark.html
    Process exited with code: ExitFailure 1

[yasu@nixos:~/disclaimer]$

**Comment by rbasso** [comment]
I guess you forgot to use "--no-nix-pure". Take a lot at the pull request again. I explained it there.

---- On Fri, 19 May 2017 08:15:07 +0900 notifications@github.com wrote ----

[yasu@nixos:~/disclaimer]$ stack bench --benchmark-arguments='--output=benchmark.html'
disclaimer-0.1.0.0: benchmarks
Running 1 benchmarks...
Benchmark bench: RUNNING...
benchmarking rectArea/unit square
time 8.809 ns (8.807 ns .. 8.811 ns)
bench: : commitBuffer: invalid argument (invalid character)
1.000 RBenchmark bench: ERROR

-- While building package disclaimer-0.1.0.0 using:
/home/yasu/.stack/setup-exe-cache/x86_64-linux-nix/Cabal-simple_mPHDZzAJ_1.24.2.0_ghc-8.0.2 --builddir=.stack-work/dist/x86_64-linux-nix/Cabal-1.24.2.0 bench bench --benchmark-options=--output=benchmark.html
Process exited with code: ExitFailure 1

[yasu@nixos:~/disclaimer]$ stack bench --benchmark-arguments='--output=/tmp/benchmark.html'
disclaimer-0.1.0.0: benchmarks
Running 1 benchmarks...
Benchmark bench: RUNNING...
benchmarking rectArea/unit square
time 8.804 ns (8.802 ns .. 8.805 ns)
bench: : commitBuffer: invalid argument (invalid character)
1.000 RBenchmark bench: ERROR

-- While building package disclaimer-0.1.0.0 using:
/home/yasu/.stack/setup-exe-cache/x86_64-linux-nix/Cabal-simple_mPHDZzAJ_1.24.2.0_ghc-8.0.2 --builddir=.stack-work/dist/x86_64-linux-nix/Cabal-1.24.2.0 bench bench --benchmark-options=--output=/tmp/benchmark.html
Process exited with code: ExitFailure 1

[yasu@nixos:~/disclaimer]$

**Comment by yugawara** [comment]
ah yes sorry realized it.  i am replying here... let's see what happens .  i wonder if github has some mechanism of relaying email replies to something else...

**Comment by rbasso** [comment]
I guess github has it. Nice! 😄

**Pull request merged**
